### ISSUE TITLE
missing: TF_LIBRARIES But the  tensorflow is installed

### ISSUE THREAD

**Issue by bnnd** [chrismile/hdrnet-viewer#1]
- LOG
```
root@ubuntu:/data/hdrnet-viewer/build# cmake ..
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find TensorFlow (missing: TF_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindTensorFlow.cmake:12 (find_package_handle_standard_args)
  CMakeLists.txt:14 (find_package)


-- Configuring incomplete, errors occurred!
See also "/data/hdrnet-viewer/build/CMakeFiles/CMakeOutput.log".
root@ubuntu:/data/hdrnet-viewer/build# echo $TF_LIBRARIES
/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow
```
- VERSION
```
root@ubuntu:/data/hdrnet-viewer/build# gcc --version;pkg-config --modversion opencv;
gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

2.4.9.1
root@ubuntu:/data/hdrnet-viewer/build# python --version
Python 2.7.14 :: Anaconda, Inc.
```

**Comment by chrismile** [comment]
Hi,

for the compilation of the program the C++ API of Tensorflow is necessary. Unfortunately, the standard Tensorflow package only contains the Python interface.

Compiling the Tensorflow C++ API can be really bothersome. If you want to read more about it:

https://stackoverflow.com/questions/33620794/how-to-build-and-use-google-tensorflow-c-api
https://github.com/FloopCZ/tensorflow_cc

I especially can recommend the second link (TensorflowCC makes compiling the C++ interface easier).

I'll update the build instructions to include this.

**Comment by chrismile** [comment]
One more thing I just noticed while building TensorflowCC a second time: The shared build of TensorflowCC is necessary, as otherwise some important parts of the API are not available.

**Comment by bnnd** [comment]
The problem of tensorflow c++ has been resolved
and then  the nsync_cv.h compiler failed and the src/GridRenderer.o could not be generated
Can you provide binaries for hdrnet-viewer?

**Comment by chrismile** [comment]
I've created an archive containing all executables, data files and necessary libraries:
https://drive.google.com/file/d/1S5nsMS4ejFTQBxqH-7GjxO5LE47uOKjx/view?usp=sharing

I tested it on Ubuntu 16.04 and Ubuntu 17.10 64-bit. However, my version of Tensorflow seems to be built with an SSE4.2 instruction set. On my older machine (Intel Core i5 from Sandy Bridge generation) I get this error message when debugging with gdb:

```
Thread 1 "hdrnetviewer" received signal SIGILL, Illegal instruction.
0x00007ffff5ea9fa1 in google::protobuf::FileOptions::MergePartialFromCodedStream(google::protobuf::CodedInputStream*) ()
   from /home/christoph/build/hdrnet-viewer/lib/libtensorflow_cc.so
```

Tell me if you have any trouble launching the application on your machine. To launch it, you need to call "run.sh" from the application directory in a command-line terminal after extracting the archive.

**Comment by chrismile** [comment]
In case the executable shouldn't work on your machine: I think I know why you couldn't build the program. Tensorflow 1.4 broke the interface and the include folders changed. I updated the CMake script to work for the new version of Tensorflow. If my pre-built executable doesn't start and you want to compile the program, this should work (I tested it on my older machine):

1. Install dependencies (like OpenCV or the dependencies for sgl - should be already done).

2. Install shared version of TensorflowCC (already done)

3. Clone sgl (https://github.com/chrismile/sgl - new version available)

```
cd sgl
mkdir build
cd build
cmake ..
make
sudo make install
```

4. Clone hdrnet-viewer (https://github.com/chrismile/hdrnet-viewer/ - new version available)

```
cd hdrnet-viewer
mkdir build
cd build
cmake ..
make
```

5. Download the pre-trained models (binary files not included in git repo):
https://drive.google.com/file/d/1CcaDfS71e57I4mxSgqPoS4Pe_4AoyDSV/view?usp=sharing
... and extract them to hdrnet-viewer/Data/pretrained_models

6. Execute the program by calling "run.sh" in the main hdrnet-viewer directory.
Maybe you need to call "chmod +x build/hdrnetviewer" beforehand to give the program rights to execute.

**Comment by ColdCodeCool** [comment]
@chrismile  hi, chris, do you have a plan to port hdrnet onto mobile phone?

**Comment by chrismile** [comment]
Hi,
unfortunately, I don't have any plans to port it to mobile phones at the moment.

It would be necessary to rewrite everything to use OpenGL ES instead of OpenGL, and to use Tensorflow Lite instead of TensorflowCC. Additionally, a completely different UI would also be necessary on mobile phones.
